apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: laravel
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: laravel-project
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
