apiVersion: v1
kind: PersistentVolume
metadata:
  name: application
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/www
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application
  labels:
    app: application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
